/*
Ais-Stream WebsocketObjects

OpenAPI 3.0 definitions for the data models used by aisstream.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aisStream

import (
	"encoding/json"
)

// LongRangeAisBroadcastMessage struct for LongRangeAisBroadcastMessage
type LongRangeAisBroadcastMessage struct {
	MessageID int32 `json:"MessageID"`
	RepeatIndicator int32 `json:"RepeatIndicator"`
	UserID int32 `json:"UserID"`
	Valid bool `json:"Valid"`
	PositionAccuracy bool `json:"PositionAccuracy"`
	Raim bool `json:"Raim"`
	NavigationalStatus int32 `json:"NavigationalStatus"`
	Longitude float64 `json:"Longitude"`
	Latitude float64 `json:"Latitude"`
	Sog float64 `json:"Sog"`
	Cog float64 `json:"Cog"`
	PositionLatency bool `json:"PositionLatency"`
	Spare bool `json:"Spare"`
}

// NewLongRangeAisBroadcastMessage instantiates a new LongRangeAisBroadcastMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLongRangeAisBroadcastMessage(messageID int32, repeatIndicator int32, userID int32, valid bool, positionAccuracy bool, raim bool, navigationalStatus int32, longitude float64, latitude float64, sog float64, cog float64, positionLatency bool, spare bool) *LongRangeAisBroadcastMessage {
	this := LongRangeAisBroadcastMessage{}
	this.MessageID = messageID
	this.RepeatIndicator = repeatIndicator
	this.UserID = userID
	this.Valid = valid
	this.PositionAccuracy = positionAccuracy
	this.Raim = raim
	this.NavigationalStatus = navigationalStatus
	this.Longitude = longitude
	this.Latitude = latitude
	this.Sog = sog
	this.Cog = cog
	this.PositionLatency = positionLatency
	this.Spare = spare
	return &this
}

// NewLongRangeAisBroadcastMessageWithDefaults instantiates a new LongRangeAisBroadcastMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLongRangeAisBroadcastMessageWithDefaults() *LongRangeAisBroadcastMessage {
	this := LongRangeAisBroadcastMessage{}
	return &this
}

// GetMessageID returns the MessageID field value
func (o *LongRangeAisBroadcastMessage) GetMessageID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MessageID
}

// GetMessageIDOk returns a tuple with the MessageID field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetMessageIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageID, true
}

// SetMessageID sets field value
func (o *LongRangeAisBroadcastMessage) SetMessageID(v int32) {
	o.MessageID = v
}

// GetRepeatIndicator returns the RepeatIndicator field value
func (o *LongRangeAisBroadcastMessage) GetRepeatIndicator() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RepeatIndicator
}

// GetRepeatIndicatorOk returns a tuple with the RepeatIndicator field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetRepeatIndicatorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepeatIndicator, true
}

// SetRepeatIndicator sets field value
func (o *LongRangeAisBroadcastMessage) SetRepeatIndicator(v int32) {
	o.RepeatIndicator = v
}

// GetUserID returns the UserID field value
func (o *LongRangeAisBroadcastMessage) GetUserID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetUserIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *LongRangeAisBroadcastMessage) SetUserID(v int32) {
	o.UserID = v
}

// GetValid returns the Valid field value
func (o *LongRangeAisBroadcastMessage) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *LongRangeAisBroadcastMessage) SetValid(v bool) {
	o.Valid = v
}

// GetPositionAccuracy returns the PositionAccuracy field value
func (o *LongRangeAisBroadcastMessage) GetPositionAccuracy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PositionAccuracy
}

// GetPositionAccuracyOk returns a tuple with the PositionAccuracy field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetPositionAccuracyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionAccuracy, true
}

// SetPositionAccuracy sets field value
func (o *LongRangeAisBroadcastMessage) SetPositionAccuracy(v bool) {
	o.PositionAccuracy = v
}

// GetRaim returns the Raim field value
func (o *LongRangeAisBroadcastMessage) GetRaim() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Raim
}

// GetRaimOk returns a tuple with the Raim field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetRaimOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raim, true
}

// SetRaim sets field value
func (o *LongRangeAisBroadcastMessage) SetRaim(v bool) {
	o.Raim = v
}

// GetNavigationalStatus returns the NavigationalStatus field value
func (o *LongRangeAisBroadcastMessage) GetNavigationalStatus() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NavigationalStatus
}

// GetNavigationalStatusOk returns a tuple with the NavigationalStatus field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetNavigationalStatusOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NavigationalStatus, true
}

// SetNavigationalStatus sets field value
func (o *LongRangeAisBroadcastMessage) SetNavigationalStatus(v int32) {
	o.NavigationalStatus = v
}

// GetLongitude returns the Longitude field value
func (o *LongRangeAisBroadcastMessage) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *LongRangeAisBroadcastMessage) SetLongitude(v float64) {
	o.Longitude = v
}

// GetLatitude returns the Latitude field value
func (o *LongRangeAisBroadcastMessage) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *LongRangeAisBroadcastMessage) SetLatitude(v float64) {
	o.Latitude = v
}

// GetSog returns the Sog field value
func (o *LongRangeAisBroadcastMessage) GetSog() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Sog
}

// GetSogOk returns a tuple with the Sog field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetSogOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sog, true
}

// SetSog sets field value
func (o *LongRangeAisBroadcastMessage) SetSog(v float64) {
	o.Sog = v
}

// GetCog returns the Cog field value
func (o *LongRangeAisBroadcastMessage) GetCog() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Cog
}

// GetCogOk returns a tuple with the Cog field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetCogOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cog, true
}

// SetCog sets field value
func (o *LongRangeAisBroadcastMessage) SetCog(v float64) {
	o.Cog = v
}

// GetPositionLatency returns the PositionLatency field value
func (o *LongRangeAisBroadcastMessage) GetPositionLatency() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PositionLatency
}

// GetPositionLatencyOk returns a tuple with the PositionLatency field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetPositionLatencyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionLatency, true
}

// SetPositionLatency sets field value
func (o *LongRangeAisBroadcastMessage) SetPositionLatency(v bool) {
	o.PositionLatency = v
}

// GetSpare returns the Spare field value
func (o *LongRangeAisBroadcastMessage) GetSpare() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Spare
}

// GetSpareOk returns a tuple with the Spare field value
// and a boolean to check if the value has been set.
func (o *LongRangeAisBroadcastMessage) GetSpareOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spare, true
}

// SetSpare sets field value
func (o *LongRangeAisBroadcastMessage) SetSpare(v bool) {
	o.Spare = v
}

func (o LongRangeAisBroadcastMessage) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MessageID"] = o.MessageID
	}
	if true {
		toSerialize["RepeatIndicator"] = o.RepeatIndicator
	}
	if true {
		toSerialize["UserID"] = o.UserID
	}
	if true {
		toSerialize["Valid"] = o.Valid
	}
	if true {
		toSerialize["PositionAccuracy"] = o.PositionAccuracy
	}
	if true {
		toSerialize["Raim"] = o.Raim
	}
	if true {
		toSerialize["NavigationalStatus"] = o.NavigationalStatus
	}
	if true {
		toSerialize["Longitude"] = o.Longitude
	}
	if true {
		toSerialize["Latitude"] = o.Latitude
	}
	if true {
		toSerialize["Sog"] = o.Sog
	}
	if true {
		toSerialize["Cog"] = o.Cog
	}
	if true {
		toSerialize["PositionLatency"] = o.PositionLatency
	}
	if true {
		toSerialize["Spare"] = o.Spare
	}
	return json.Marshal(toSerialize)
}

type NullableLongRangeAisBroadcastMessage struct {
	value *LongRangeAisBroadcastMessage
	isSet bool
}

func (v NullableLongRangeAisBroadcastMessage) Get() *LongRangeAisBroadcastMessage {
	return v.value
}

func (v *NullableLongRangeAisBroadcastMessage) Set(val *LongRangeAisBroadcastMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableLongRangeAisBroadcastMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableLongRangeAisBroadcastMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLongRangeAisBroadcastMessage(val *LongRangeAisBroadcastMessage) *NullableLongRangeAisBroadcastMessage {
	return &NullableLongRangeAisBroadcastMessage{value: val, isSet: true}
}

func (v NullableLongRangeAisBroadcastMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLongRangeAisBroadcastMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


