/*
Ais-Stream WebsocketObjects

OpenAPI 3.0 definitions for the data models used by aisstream.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aisStream

import (
	"encoding/json"
)

// ChannelManagementUnicast struct for ChannelManagementUnicast
type ChannelManagementUnicast struct {
	AddressStation1 int32 `json:"AddressStation1"`
	Spare2 int32 `json:"Spare2"`
	AddressStation2 int32 `json:"AddressStation2"`
	Spare3 int32 `json:"Spare3"`
}

// NewChannelManagementUnicast instantiates a new ChannelManagementUnicast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelManagementUnicast(addressStation1 int32, spare2 int32, addressStation2 int32, spare3 int32) *ChannelManagementUnicast {
	this := ChannelManagementUnicast{}
	this.AddressStation1 = addressStation1
	this.Spare2 = spare2
	this.AddressStation2 = addressStation2
	this.Spare3 = spare3
	return &this
}

// NewChannelManagementUnicastWithDefaults instantiates a new ChannelManagementUnicast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelManagementUnicastWithDefaults() *ChannelManagementUnicast {
	this := ChannelManagementUnicast{}
	return &this
}

// GetAddressStation1 returns the AddressStation1 field value
func (o *ChannelManagementUnicast) GetAddressStation1() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AddressStation1
}

// GetAddressStation1Ok returns a tuple with the AddressStation1 field value
// and a boolean to check if the value has been set.
func (o *ChannelManagementUnicast) GetAddressStation1Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressStation1, true
}

// SetAddressStation1 sets field value
func (o *ChannelManagementUnicast) SetAddressStation1(v int32) {
	o.AddressStation1 = v
}

// GetSpare2 returns the Spare2 field value
func (o *ChannelManagementUnicast) GetSpare2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spare2
}

// GetSpare2Ok returns a tuple with the Spare2 field value
// and a boolean to check if the value has been set.
func (o *ChannelManagementUnicast) GetSpare2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spare2, true
}

// SetSpare2 sets field value
func (o *ChannelManagementUnicast) SetSpare2(v int32) {
	o.Spare2 = v
}

// GetAddressStation2 returns the AddressStation2 field value
func (o *ChannelManagementUnicast) GetAddressStation2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AddressStation2
}

// GetAddressStation2Ok returns a tuple with the AddressStation2 field value
// and a boolean to check if the value has been set.
func (o *ChannelManagementUnicast) GetAddressStation2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AddressStation2, true
}

// SetAddressStation2 sets field value
func (o *ChannelManagementUnicast) SetAddressStation2(v int32) {
	o.AddressStation2 = v
}

// GetSpare3 returns the Spare3 field value
func (o *ChannelManagementUnicast) GetSpare3() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spare3
}

// GetSpare3Ok returns a tuple with the Spare3 field value
// and a boolean to check if the value has been set.
func (o *ChannelManagementUnicast) GetSpare3Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spare3, true
}

// SetSpare3 sets field value
func (o *ChannelManagementUnicast) SetSpare3(v int32) {
	o.Spare3 = v
}

func (o ChannelManagementUnicast) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["AddressStation1"] = o.AddressStation1
	}
	if true {
		toSerialize["Spare2"] = o.Spare2
	}
	if true {
		toSerialize["AddressStation2"] = o.AddressStation2
	}
	if true {
		toSerialize["Spare3"] = o.Spare3
	}
	return json.Marshal(toSerialize)
}

type NullableChannelManagementUnicast struct {
	value *ChannelManagementUnicast
	isSet bool
}

func (v NullableChannelManagementUnicast) Get() *ChannelManagementUnicast {
	return v.value
}

func (v *NullableChannelManagementUnicast) Set(val *ChannelManagementUnicast) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelManagementUnicast) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelManagementUnicast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelManagementUnicast(val *ChannelManagementUnicast) *NullableChannelManagementUnicast {
	return &NullableChannelManagementUnicast{value: val, isSet: true}
}

func (v NullableChannelManagementUnicast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelManagementUnicast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


