/*
Ais-Stream WebsocketObjects

OpenAPI 3.0 definitions for the data models used by aisstream.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aisStream

import (
	"encoding/json"
)

// StaticDataReportReportA struct for StaticDataReportReportA
type StaticDataReportReportA struct {
	Valid bool `json:"Valid"`
	Name string `json:"Name"`
}

// NewStaticDataReportReportA instantiates a new StaticDataReportReportA object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStaticDataReportReportA(valid bool, name string) *StaticDataReportReportA {
	this := StaticDataReportReportA{}
	this.Valid = valid
	this.Name = name
	return &this
}

// NewStaticDataReportReportAWithDefaults instantiates a new StaticDataReportReportA object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStaticDataReportReportAWithDefaults() *StaticDataReportReportA {
	this := StaticDataReportReportA{}
	return &this
}

// GetValid returns the Valid field value
func (o *StaticDataReportReportA) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *StaticDataReportReportA) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *StaticDataReportReportA) SetValid(v bool) {
	o.Valid = v
}

// GetName returns the Name field value
func (o *StaticDataReportReportA) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StaticDataReportReportA) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StaticDataReportReportA) SetName(v string) {
	o.Name = v
}

func (o StaticDataReportReportA) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["Valid"] = o.Valid
	}
	if true {
		toSerialize["Name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableStaticDataReportReportA struct {
	value *StaticDataReportReportA
	isSet bool
}

func (v NullableStaticDataReportReportA) Get() *StaticDataReportReportA {
	return v.value
}

func (v *NullableStaticDataReportReportA) Set(val *StaticDataReportReportA) {
	v.value = val
	v.isSet = true
}

func (v NullableStaticDataReportReportA) IsSet() bool {
	return v.isSet
}

func (v *NullableStaticDataReportReportA) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStaticDataReportReportA(val *StaticDataReportReportA) *NullableStaticDataReportReportA {
	return &NullableStaticDataReportReportA{value: val, isSet: true}
}

func (v NullableStaticDataReportReportA) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStaticDataReportReportA) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


