/*
Ais-Stream WebsocketObjects

OpenAPI 3.0 definitions for the data models used by aisstream.io.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package aisStream

import (
	"encoding/json"
)

// StandardClassBPositionReport struct for StandardClassBPositionReport
type StandardClassBPositionReport struct {
	MessageID int32 `json:"MessageID"`
	RepeatIndicator int32 `json:"RepeatIndicator"`
	UserID int32 `json:"UserID"`
	Valid bool `json:"Valid"`
	Spare1 int32 `json:"Spare1"`
	Sog float64 `json:"Sog"`
	PositionAccuracy bool `json:"PositionAccuracy"`
	Longitude float64 `json:"Longitude"`
	Latitude float64 `json:"Latitude"`
	Cog float64 `json:"Cog"`
	TrueHeading int32 `json:"TrueHeading"`
	Timestamp int32 `json:"Timestamp"`
	Spare2 int32 `json:"Spare2"`
	ClassBUnit bool `json:"ClassBUnit"`
	ClassBDisplay bool `json:"ClassBDisplay"`
	ClassBDsc bool `json:"ClassBDsc"`
	ClassBBand bool `json:"ClassBBand"`
	ClassBMsg22 bool `json:"ClassBMsg22"`
	AssignedMode bool `json:"AssignedMode"`
	Raim bool `json:"Raim"`
	CommunicationStateIsItdma bool `json:"CommunicationStateIsItdma"`
	CommunicationState int32 `json:"CommunicationState"`
}

// NewStandardClassBPositionReport instantiates a new StandardClassBPositionReport object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStandardClassBPositionReport(messageID int32, repeatIndicator int32, userID int32, valid bool, spare1 int32, sog float64, positionAccuracy bool, longitude float64, latitude float64, cog float64, trueHeading int32, timestamp int32, spare2 int32, classBUnit bool, classBDisplay bool, classBDsc bool, classBBand bool, classBMsg22 bool, assignedMode bool, raim bool, communicationStateIsItdma bool, communicationState int32) *StandardClassBPositionReport {
	this := StandardClassBPositionReport{}
	this.MessageID = messageID
	this.RepeatIndicator = repeatIndicator
	this.UserID = userID
	this.Valid = valid
	this.Spare1 = spare1
	this.Sog = sog
	this.PositionAccuracy = positionAccuracy
	this.Longitude = longitude
	this.Latitude = latitude
	this.Cog = cog
	this.TrueHeading = trueHeading
	this.Timestamp = timestamp
	this.Spare2 = spare2
	this.ClassBUnit = classBUnit
	this.ClassBDisplay = classBDisplay
	this.ClassBDsc = classBDsc
	this.ClassBBand = classBBand
	this.ClassBMsg22 = classBMsg22
	this.AssignedMode = assignedMode
	this.Raim = raim
	this.CommunicationStateIsItdma = communicationStateIsItdma
	this.CommunicationState = communicationState
	return &this
}

// NewStandardClassBPositionReportWithDefaults instantiates a new StandardClassBPositionReport object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStandardClassBPositionReportWithDefaults() *StandardClassBPositionReport {
	this := StandardClassBPositionReport{}
	return &this
}

// GetMessageID returns the MessageID field value
func (o *StandardClassBPositionReport) GetMessageID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MessageID
}

// GetMessageIDOk returns a tuple with the MessageID field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetMessageIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MessageID, true
}

// SetMessageID sets field value
func (o *StandardClassBPositionReport) SetMessageID(v int32) {
	o.MessageID = v
}

// GetRepeatIndicator returns the RepeatIndicator field value
func (o *StandardClassBPositionReport) GetRepeatIndicator() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RepeatIndicator
}

// GetRepeatIndicatorOk returns a tuple with the RepeatIndicator field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetRepeatIndicatorOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepeatIndicator, true
}

// SetRepeatIndicator sets field value
func (o *StandardClassBPositionReport) SetRepeatIndicator(v int32) {
	o.RepeatIndicator = v
}

// GetUserID returns the UserID field value
func (o *StandardClassBPositionReport) GetUserID() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserID
}

// GetUserIDOk returns a tuple with the UserID field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetUserIDOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserID, true
}

// SetUserID sets field value
func (o *StandardClassBPositionReport) SetUserID(v int32) {
	o.UserID = v
}

// GetValid returns the Valid field value
func (o *StandardClassBPositionReport) GetValid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Valid
}

// GetValidOk returns a tuple with the Valid field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetValidOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Valid, true
}

// SetValid sets field value
func (o *StandardClassBPositionReport) SetValid(v bool) {
	o.Valid = v
}

// GetSpare1 returns the Spare1 field value
func (o *StandardClassBPositionReport) GetSpare1() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spare1
}

// GetSpare1Ok returns a tuple with the Spare1 field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetSpare1Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spare1, true
}

// SetSpare1 sets field value
func (o *StandardClassBPositionReport) SetSpare1(v int32) {
	o.Spare1 = v
}

// GetSog returns the Sog field value
func (o *StandardClassBPositionReport) GetSog() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Sog
}

// GetSogOk returns a tuple with the Sog field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetSogOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sog, true
}

// SetSog sets field value
func (o *StandardClassBPositionReport) SetSog(v float64) {
	o.Sog = v
}

// GetPositionAccuracy returns the PositionAccuracy field value
func (o *StandardClassBPositionReport) GetPositionAccuracy() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.PositionAccuracy
}

// GetPositionAccuracyOk returns a tuple with the PositionAccuracy field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetPositionAccuracyOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PositionAccuracy, true
}

// SetPositionAccuracy sets field value
func (o *StandardClassBPositionReport) SetPositionAccuracy(v bool) {
	o.PositionAccuracy = v
}

// GetLongitude returns the Longitude field value
func (o *StandardClassBPositionReport) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *StandardClassBPositionReport) SetLongitude(v float64) {
	o.Longitude = v
}

// GetLatitude returns the Latitude field value
func (o *StandardClassBPositionReport) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *StandardClassBPositionReport) SetLatitude(v float64) {
	o.Latitude = v
}

// GetCog returns the Cog field value
func (o *StandardClassBPositionReport) GetCog() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Cog
}

// GetCogOk returns a tuple with the Cog field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetCogOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cog, true
}

// SetCog sets field value
func (o *StandardClassBPositionReport) SetCog(v float64) {
	o.Cog = v
}

// GetTrueHeading returns the TrueHeading field value
func (o *StandardClassBPositionReport) GetTrueHeading() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TrueHeading
}

// GetTrueHeadingOk returns a tuple with the TrueHeading field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetTrueHeadingOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrueHeading, true
}

// SetTrueHeading sets field value
func (o *StandardClassBPositionReport) SetTrueHeading(v int32) {
	o.TrueHeading = v
}

// GetTimestamp returns the Timestamp field value
func (o *StandardClassBPositionReport) GetTimestamp() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetTimestampOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *StandardClassBPositionReport) SetTimestamp(v int32) {
	o.Timestamp = v
}

// GetSpare2 returns the Spare2 field value
func (o *StandardClassBPositionReport) GetSpare2() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Spare2
}

// GetSpare2Ok returns a tuple with the Spare2 field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetSpare2Ok() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Spare2, true
}

// SetSpare2 sets field value
func (o *StandardClassBPositionReport) SetSpare2(v int32) {
	o.Spare2 = v
}

// GetClassBUnit returns the ClassBUnit field value
func (o *StandardClassBPositionReport) GetClassBUnit() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassBUnit
}

// GetClassBUnitOk returns a tuple with the ClassBUnit field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetClassBUnitOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassBUnit, true
}

// SetClassBUnit sets field value
func (o *StandardClassBPositionReport) SetClassBUnit(v bool) {
	o.ClassBUnit = v
}

// GetClassBDisplay returns the ClassBDisplay field value
func (o *StandardClassBPositionReport) GetClassBDisplay() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassBDisplay
}

// GetClassBDisplayOk returns a tuple with the ClassBDisplay field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetClassBDisplayOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassBDisplay, true
}

// SetClassBDisplay sets field value
func (o *StandardClassBPositionReport) SetClassBDisplay(v bool) {
	o.ClassBDisplay = v
}

// GetClassBDsc returns the ClassBDsc field value
func (o *StandardClassBPositionReport) GetClassBDsc() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassBDsc
}

// GetClassBDscOk returns a tuple with the ClassBDsc field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetClassBDscOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassBDsc, true
}

// SetClassBDsc sets field value
func (o *StandardClassBPositionReport) SetClassBDsc(v bool) {
	o.ClassBDsc = v
}

// GetClassBBand returns the ClassBBand field value
func (o *StandardClassBPositionReport) GetClassBBand() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassBBand
}

// GetClassBBandOk returns a tuple with the ClassBBand field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetClassBBandOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassBBand, true
}

// SetClassBBand sets field value
func (o *StandardClassBPositionReport) SetClassBBand(v bool) {
	o.ClassBBand = v
}

// GetClassBMsg22 returns the ClassBMsg22 field value
func (o *StandardClassBPositionReport) GetClassBMsg22() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ClassBMsg22
}

// GetClassBMsg22Ok returns a tuple with the ClassBMsg22 field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetClassBMsg22Ok() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassBMsg22, true
}

// SetClassBMsg22 sets field value
func (o *StandardClassBPositionReport) SetClassBMsg22(v bool) {
	o.ClassBMsg22 = v
}

// GetAssignedMode returns the AssignedMode field value
func (o *StandardClassBPositionReport) GetAssignedMode() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AssignedMode
}

// GetAssignedModeOk returns a tuple with the AssignedMode field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetAssignedModeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssignedMode, true
}

// SetAssignedMode sets field value
func (o *StandardClassBPositionReport) SetAssignedMode(v bool) {
	o.AssignedMode = v
}

// GetRaim returns the Raim field value
func (o *StandardClassBPositionReport) GetRaim() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Raim
}

// GetRaimOk returns a tuple with the Raim field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetRaimOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Raim, true
}

// SetRaim sets field value
func (o *StandardClassBPositionReport) SetRaim(v bool) {
	o.Raim = v
}

// GetCommunicationStateIsItdma returns the CommunicationStateIsItdma field value
func (o *StandardClassBPositionReport) GetCommunicationStateIsItdma() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.CommunicationStateIsItdma
}

// GetCommunicationStateIsItdmaOk returns a tuple with the CommunicationStateIsItdma field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetCommunicationStateIsItdmaOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommunicationStateIsItdma, true
}

// SetCommunicationStateIsItdma sets field value
func (o *StandardClassBPositionReport) SetCommunicationStateIsItdma(v bool) {
	o.CommunicationStateIsItdma = v
}

// GetCommunicationState returns the CommunicationState field value
func (o *StandardClassBPositionReport) GetCommunicationState() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CommunicationState
}

// GetCommunicationStateOk returns a tuple with the CommunicationState field value
// and a boolean to check if the value has been set.
func (o *StandardClassBPositionReport) GetCommunicationStateOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CommunicationState, true
}

// SetCommunicationState sets field value
func (o *StandardClassBPositionReport) SetCommunicationState(v int32) {
	o.CommunicationState = v
}

func (o StandardClassBPositionReport) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["MessageID"] = o.MessageID
	}
	if true {
		toSerialize["RepeatIndicator"] = o.RepeatIndicator
	}
	if true {
		toSerialize["UserID"] = o.UserID
	}
	if true {
		toSerialize["Valid"] = o.Valid
	}
	if true {
		toSerialize["Spare1"] = o.Spare1
	}
	if true {
		toSerialize["Sog"] = o.Sog
	}
	if true {
		toSerialize["PositionAccuracy"] = o.PositionAccuracy
	}
	if true {
		toSerialize["Longitude"] = o.Longitude
	}
	if true {
		toSerialize["Latitude"] = o.Latitude
	}
	if true {
		toSerialize["Cog"] = o.Cog
	}
	if true {
		toSerialize["TrueHeading"] = o.TrueHeading
	}
	if true {
		toSerialize["Timestamp"] = o.Timestamp
	}
	if true {
		toSerialize["Spare2"] = o.Spare2
	}
	if true {
		toSerialize["ClassBUnit"] = o.ClassBUnit
	}
	if true {
		toSerialize["ClassBDisplay"] = o.ClassBDisplay
	}
	if true {
		toSerialize["ClassBDsc"] = o.ClassBDsc
	}
	if true {
		toSerialize["ClassBBand"] = o.ClassBBand
	}
	if true {
		toSerialize["ClassBMsg22"] = o.ClassBMsg22
	}
	if true {
		toSerialize["AssignedMode"] = o.AssignedMode
	}
	if true {
		toSerialize["Raim"] = o.Raim
	}
	if true {
		toSerialize["CommunicationStateIsItdma"] = o.CommunicationStateIsItdma
	}
	if true {
		toSerialize["CommunicationState"] = o.CommunicationState
	}
	return json.Marshal(toSerialize)
}

type NullableStandardClassBPositionReport struct {
	value *StandardClassBPositionReport
	isSet bool
}

func (v NullableStandardClassBPositionReport) Get() *StandardClassBPositionReport {
	return v.value
}

func (v *NullableStandardClassBPositionReport) Set(val *StandardClassBPositionReport) {
	v.value = val
	v.isSet = true
}

func (v NullableStandardClassBPositionReport) IsSet() bool {
	return v.isSet
}

func (v *NullableStandardClassBPositionReport) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStandardClassBPositionReport(val *StandardClassBPositionReport) *NullableStandardClassBPositionReport {
	return &NullableStandardClassBPositionReport{value: val, isSet: true}
}

func (v NullableStandardClassBPositionReport) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStandardClassBPositionReport) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


