"""
    Ais-Stream WebsocketObjects

    OpenAPI 3.0 definitions for the data models used by aisstream.io.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.unknown_message import UnknownMessage


class TestUnknownMessage(unittest.TestCase):
    """UnknownMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnknownMessage(self):
        """Test UnknownMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UnknownMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
