"""
    Ais-Stream WebsocketObjects

    A sample API to illustrate OpenAPI concepts  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.ship_static_data_dimension import ShipStaticDataDimension
globals()['ShipStaticDataDimension'] = ShipStaticDataDimension
from aisStream.model.static_data_report_report_b import StaticDataReportReportB


class TestStaticDataReportReportB(unittest.TestCase):
    """StaticDataReportReportB unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStaticDataReportReportB(self):
        """Test StaticDataReportReportB"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StaticDataReportReportB()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
