"""
    Ais-Stream WebsocketObjects

    OpenAPI 3.0 definitions for the data models used by aisstream.io.  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.error import Error


class TestError(unittest.TestCase):
    """Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testError(self):
        """Test Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
