"""
    Ais-Stream WebsocketObjects

    A sample API to illustrate OpenAPI concepts  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.standard_search_and_rescue_aircraft_report import StandardSearchAndRescueAircraftReport


class TestStandardSearchAndRescueAircraftReport(unittest.TestCase):
    """StandardSearchAndRescueAircraftReport unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStandardSearchAndRescueAircraftReport(self):
        """Test StandardSearchAndRescueAircraftReport"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StandardSearchAndRescueAircraftReport()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
