"""
    Ais-Stream WebsocketObjects

    A sample API to illustrate OpenAPI concepts  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.binary_acknowledge_destinations0 import BinaryAcknowledgeDestinations0
globals()['BinaryAcknowledgeDestinations0'] = BinaryAcknowledgeDestinations0
from aisStream.model.binary_acknowledge_destinations import BinaryAcknowledgeDestinations


class TestBinaryAcknowledgeDestinations(unittest.TestCase):
    """BinaryAcknowledgeDestinations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBinaryAcknowledgeDestinations(self):
        """Test BinaryAcknowledgeDestinations"""
        # FIXME: construct object with mandatory attributes with example values
        # model = BinaryAcknowledgeDestinations()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
