"""
    Ais-Stream WebsocketObjects

    A sample API to illustrate OpenAPI concepts  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.addressed_binary_message_application_id import AddressedBinaryMessageApplicationID
globals()['AddressedBinaryMessageApplicationID'] = AddressedBinaryMessageApplicationID
from aisStream.model.multi_slot_binary_message import MultiSlotBinaryMessage


class TestMultiSlotBinaryMessage(unittest.TestCase):
    """MultiSlotBinaryMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMultiSlotBinaryMessage(self):
        """Test MultiSlotBinaryMessage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MultiSlotBinaryMessage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
