"""
    Ais-Stream WebsocketObjects

    A sample API to illustrate OpenAPI concepts  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import aisStream
from aisStream.model.group_assignment_command import GroupAssignmentCommand


class TestGroupAssignmentCommand(unittest.TestCase):
    """GroupAssignmentCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGroupAssignmentCommand(self):
        """Test GroupAssignmentCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = GroupAssignmentCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
