/*
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ChannelManagementUnicast
 */
public class ChannelManagementUnicastTest {
    private final ChannelManagementUnicast model = new ChannelManagementUnicast();

    /**
     * Model tests for ChannelManagementUnicast
     */
    @Test
    public void testChannelManagementUnicast() {
        // TODO: test ChannelManagementUnicast
    }

    /**
     * Test the property 'addressStation1'
     */
    @Test
    public void addressStation1Test() {
        // TODO: test addressStation1
    }

    /**
     * Test the property 'spare2'
     */
    @Test
    public void spare2Test() {
        // TODO: test spare2
    }

    /**
     * Test the property 'addressStation2'
     */
    @Test
    public void addressStation2Test() {
        // TODO: test addressStation2
    }

    /**
     * Test the property 'spare3'
     */
    @Test
    public void spare3Test() {
        // TODO: test spare3
    }

}
