/*
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for InterrogationStation2
 */
public class InterrogationStation2Test {
    private final InterrogationStation2 model = new InterrogationStation2();

    /**
     * Model tests for InterrogationStation2
     */
    @Test
    public void testInterrogationStation2() {
        // TODO: test InterrogationStation2
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'spare1'
     */
    @Test
    public void spare1Test() {
        // TODO: test spare1
    }

    /**
     * Test the property 'stationID'
     */
    @Test
    public void stationIDTest() {
        // TODO: test stationID
    }

    /**
     * Test the property 'messageID'
     */
    @Test
    public void messageIDTest() {
        // TODO: test messageID
    }

    /**
     * Test the property 'slotOffset'
     */
    @Test
    public void slotOffsetTest() {
        // TODO: test slotOffset
    }

    /**
     * Test the property 'spare2'
     */
    @Test
    public void spare2Test() {
        // TODO: test spare2
    }

}
