/*
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.InterrogationStation1Msg1;
import org.openapitools.client.model.InterrogationStation1Msg2;
import org.openapitools.client.model.InterrogationStation2;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Interrogation
 */
public class InterrogationTest {
    private final Interrogation model = new Interrogation();

    /**
     * Model tests for Interrogation
     */
    @Test
    public void testInterrogation() {
        // TODO: test Interrogation
    }

    /**
     * Test the property 'messageID'
     */
    @Test
    public void messageIDTest() {
        // TODO: test messageID
    }

    /**
     * Test the property 'repeatIndicator'
     */
    @Test
    public void repeatIndicatorTest() {
        // TODO: test repeatIndicator
    }

    /**
     * Test the property 'userID'
     */
    @Test
    public void userIDTest() {
        // TODO: test userID
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'spare'
     */
    @Test
    public void spareTest() {
        // TODO: test spare
    }

    /**
     * Test the property 'station1Msg1'
     */
    @Test
    public void station1Msg1Test() {
        // TODO: test station1Msg1
    }

    /**
     * Test the property 'station1Msg2'
     */
    @Test
    public void station1Msg2Test() {
        // TODO: test station1Msg2
    }

    /**
     * Test the property 'station2'
     */
    @Test
    public void station2Test() {
        // TODO: test station2
    }

}
