/*
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ShipStaticDataEta
 */
public class ShipStaticDataEtaTest {
    private final ShipStaticDataEta model = new ShipStaticDataEta();

    /**
     * Model tests for ShipStaticDataEta
     */
    @Test
    public void testShipStaticDataEta() {
        // TODO: test ShipStaticDataEta
    }

    /**
     * Test the property 'month'
     */
    @Test
    public void monthTest() {
        // TODO: test month
    }

    /**
     * Test the property 'day'
     */
    @Test
    public void dayTest() {
        // TODO: test day
    }

    /**
     * Test the property 'hour'
     */
    @Test
    public void hourTest() {
        // TODO: test hour
    }

    /**
     * Test the property 'minute'
     */
    @Test
    public void minuteTest() {
        // TODO: test minute
    }

}
