/*
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ShipStaticDataDimension;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for StaticDataReportReportB
 */
public class StaticDataReportReportBTest {
    private final StaticDataReportReportB model = new StaticDataReportReportB();

    /**
     * Model tests for StaticDataReportReportB
     */
    @Test
    public void testStaticDataReportReportB() {
        // TODO: test StaticDataReportReportB
    }

    /**
     * Test the property 'valid'
     */
    @Test
    public void validTest() {
        // TODO: test valid
    }

    /**
     * Test the property 'shipType'
     */
    @Test
    public void shipTypeTest() {
        // TODO: test shipType
    }

    /**
     * Test the property 'vendorIDName'
     */
    @Test
    public void vendorIDNameTest() {
        // TODO: test vendorIDName
    }

    /**
     * Test the property 'venderIDModel'
     */
    @Test
    public void venderIDModelTest() {
        // TODO: test venderIDModel
    }

    /**
     * Test the property 'venderIDSerial'
     */
    @Test
    public void venderIDSerialTest() {
        // TODO: test venderIDSerial
    }

    /**
     * Test the property 'callSign'
     */
    @Test
    public void callSignTest() {
        // TODO: test callSign
    }

    /**
     * Test the property 'dimension'
     */
    @Test
    public void dimensionTest() {
        // TODO: test dimension
    }

    /**
     * Test the property 'fixType'
     */
    @Test
    public void fixTypeTest() {
        // TODO: test fixType
    }

    /**
     * Test the property 'spare'
     */
    @Test
    public void spareTest() {
        // TODO: test spare
    }

}
