/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace aisStream.Model
{
    /// <summary>
    /// AddressedBinaryMessageApplicationID
    /// </summary>
    [DataContract(Name = "AddressedBinaryMessage_ApplicationID")]
    public partial class AddressedBinaryMessageApplicationID : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressedBinaryMessageApplicationID" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AddressedBinaryMessageApplicationID() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AddressedBinaryMessageApplicationID" /> class.
        /// </summary>
        /// <param name="valid">valid (required).</param>
        /// <param name="designatedAreaCode">designatedAreaCode (required).</param>
        /// <param name="functionIdentifier">functionIdentifier (required).</param>
        public AddressedBinaryMessageApplicationID(bool valid = default(bool), int designatedAreaCode = default(int), int functionIdentifier = default(int))
        {
            this.Valid = valid;
            this.DesignatedAreaCode = designatedAreaCode;
            this.FunctionIdentifier = functionIdentifier;
        }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name = "Valid", IsRequired = true, EmitDefaultValue = true)]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets DesignatedAreaCode
        /// </summary>
        [DataMember(Name = "DesignatedAreaCode", IsRequired = true, EmitDefaultValue = true)]
        public int DesignatedAreaCode { get; set; }

        /// <summary>
        /// Gets or Sets FunctionIdentifier
        /// </summary>
        [DataMember(Name = "FunctionIdentifier", IsRequired = true, EmitDefaultValue = true)]
        public int FunctionIdentifier { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AddressedBinaryMessageApplicationID {\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  DesignatedAreaCode: ").Append(DesignatedAreaCode).Append("\n");
            sb.Append("  FunctionIdentifier: ").Append(FunctionIdentifier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
