/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace aisStream.Model
{
    /// <summary>
    /// LongRangeAisBroadcastMessage
    /// </summary>
    [DataContract(Name = "LongRangeAisBroadcastMessage")]
    public partial class LongRangeAisBroadcastMessage : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LongRangeAisBroadcastMessage" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected LongRangeAisBroadcastMessage() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="LongRangeAisBroadcastMessage" /> class.
        /// </summary>
        /// <param name="messageID">messageID (required).</param>
        /// <param name="repeatIndicator">repeatIndicator (required).</param>
        /// <param name="userID">userID (required).</param>
        /// <param name="valid">valid (required).</param>
        /// <param name="positionAccuracy">positionAccuracy (required).</param>
        /// <param name="raim">raim (required).</param>
        /// <param name="navigationalStatus">navigationalStatus (required).</param>
        /// <param name="longitude">longitude (required).</param>
        /// <param name="latitude">latitude (required).</param>
        /// <param name="sog">sog (required).</param>
        /// <param name="cog">cog (required).</param>
        /// <param name="positionLatency">positionLatency (required).</param>
        /// <param name="spare">spare (required).</param>
        public LongRangeAisBroadcastMessage(int messageID = default(int), int repeatIndicator = default(int), int userID = default(int), bool valid = default(bool), bool positionAccuracy = default(bool), bool raim = default(bool), int navigationalStatus = default(int), double longitude = default(double), double latitude = default(double), double sog = default(double), double cog = default(double), bool positionLatency = default(bool), bool spare = default(bool))
        {
            this.MessageID = messageID;
            this.RepeatIndicator = repeatIndicator;
            this.UserID = userID;
            this.Valid = valid;
            this.PositionAccuracy = positionAccuracy;
            this.Raim = raim;
            this.NavigationalStatus = navigationalStatus;
            this.Longitude = longitude;
            this.Latitude = latitude;
            this.Sog = sog;
            this.Cog = cog;
            this.PositionLatency = positionLatency;
            this.Spare = spare;
        }

        /// <summary>
        /// Gets or Sets MessageID
        /// </summary>
        [DataMember(Name = "MessageID", IsRequired = true, EmitDefaultValue = true)]
        public int MessageID { get; set; }

        /// <summary>
        /// Gets or Sets RepeatIndicator
        /// </summary>
        [DataMember(Name = "RepeatIndicator", IsRequired = true, EmitDefaultValue = true)]
        public int RepeatIndicator { get; set; }

        /// <summary>
        /// Gets or Sets UserID
        /// </summary>
        [DataMember(Name = "UserID", IsRequired = true, EmitDefaultValue = true)]
        public int UserID { get; set; }

        /// <summary>
        /// Gets or Sets Valid
        /// </summary>
        [DataMember(Name = "Valid", IsRequired = true, EmitDefaultValue = true)]
        public bool Valid { get; set; }

        /// <summary>
        /// Gets or Sets PositionAccuracy
        /// </summary>
        [DataMember(Name = "PositionAccuracy", IsRequired = true, EmitDefaultValue = true)]
        public bool PositionAccuracy { get; set; }

        /// <summary>
        /// Gets or Sets Raim
        /// </summary>
        [DataMember(Name = "Raim", IsRequired = true, EmitDefaultValue = true)]
        public bool Raim { get; set; }

        /// <summary>
        /// Gets or Sets NavigationalStatus
        /// </summary>
        [DataMember(Name = "NavigationalStatus", IsRequired = true, EmitDefaultValue = true)]
        public int NavigationalStatus { get; set; }

        /// <summary>
        /// Gets or Sets Longitude
        /// </summary>
        [DataMember(Name = "Longitude", IsRequired = true, EmitDefaultValue = true)]
        public double Longitude { get; set; }

        /// <summary>
        /// Gets or Sets Latitude
        /// </summary>
        [DataMember(Name = "Latitude", IsRequired = true, EmitDefaultValue = true)]
        public double Latitude { get; set; }

        /// <summary>
        /// Gets or Sets Sog
        /// </summary>
        [DataMember(Name = "Sog", IsRequired = true, EmitDefaultValue = true)]
        public double Sog { get; set; }

        /// <summary>
        /// Gets or Sets Cog
        /// </summary>
        [DataMember(Name = "Cog", IsRequired = true, EmitDefaultValue = true)]
        public double Cog { get; set; }

        /// <summary>
        /// Gets or Sets PositionLatency
        /// </summary>
        [DataMember(Name = "PositionLatency", IsRequired = true, EmitDefaultValue = true)]
        public bool PositionLatency { get; set; }

        /// <summary>
        /// Gets or Sets Spare
        /// </summary>
        [DataMember(Name = "Spare", IsRequired = true, EmitDefaultValue = true)]
        public bool Spare { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class LongRangeAisBroadcastMessage {\n");
            sb.Append("  MessageID: ").Append(MessageID).Append("\n");
            sb.Append("  RepeatIndicator: ").Append(RepeatIndicator).Append("\n");
            sb.Append("  UserID: ").Append(UserID).Append("\n");
            sb.Append("  Valid: ").Append(Valid).Append("\n");
            sb.Append("  PositionAccuracy: ").Append(PositionAccuracy).Append("\n");
            sb.Append("  Raim: ").Append(Raim).Append("\n");
            sb.Append("  NavigationalStatus: ").Append(NavigationalStatus).Append("\n");
            sb.Append("  Longitude: ").Append(Longitude).Append("\n");
            sb.Append("  Latitude: ").Append(Latitude).Append("\n");
            sb.Append("  Sog: ").Append(Sog).Append("\n");
            sb.Append("  Cog: ").Append(Cog).Append("\n");
            sb.Append("  PositionLatency: ").Append(PositionLatency).Append("\n");
            sb.Append("  Spare: ").Append(Spare).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
