/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace aisStream.Model
{
    /// <summary>
    /// ShipStaticDataEta
    /// </summary>
    [DataContract(Name = "ShipStaticData_Eta")]
    public partial class ShipStaticDataEta : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipStaticDataEta" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ShipStaticDataEta() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ShipStaticDataEta" /> class.
        /// </summary>
        /// <param name="month">month (required).</param>
        /// <param name="day">day (required).</param>
        /// <param name="hour">hour (required).</param>
        /// <param name="minute">minute (required).</param>
        public ShipStaticDataEta(int month = default(int), int day = default(int), int hour = default(int), int minute = default(int))
        {
            this.Month = month;
            this.Day = day;
            this.Hour = hour;
            this.Minute = minute;
        }

        /// <summary>
        /// Gets or Sets Month
        /// </summary>
        [DataMember(Name = "Month", IsRequired = true, EmitDefaultValue = true)]
        public int Month { get; set; }

        /// <summary>
        /// Gets or Sets Day
        /// </summary>
        [DataMember(Name = "Day", IsRequired = true, EmitDefaultValue = true)]
        public int Day { get; set; }

        /// <summary>
        /// Gets or Sets Hour
        /// </summary>
        [DataMember(Name = "Hour", IsRequired = true, EmitDefaultValue = true)]
        public int Hour { get; set; }

        /// <summary>
        /// Gets or Sets Minute
        /// </summary>
        [DataMember(Name = "Minute", IsRequired = true, EmitDefaultValue = true)]
        public int Minute { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ShipStaticDataEta {\n");
            sb.Append("  Month: ").Append(Month).Append("\n");
            sb.Append("  Day: ").Append(Day).Append("\n");
            sb.Append("  Hour: ").Append(Hour).Append("\n");
            sb.Append("  Minute: ").Append(Minute).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
