/**
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AddressedBinaryMessageApplicationID {
    'valid': boolean;
    'designatedAreaCode': number;
    'functionIdentifier': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "valid",
            "baseName": "Valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "designatedAreaCode",
            "baseName": "DesignatedAreaCode",
            "type": "number",
            "format": ""
        },
        {
            "name": "functionIdentifier",
            "baseName": "FunctionIdentifier",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddressedBinaryMessageApplicationID.attributeTypeMap;
    }

    public constructor() {
    }
}

