/**
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressedBinaryMessage } from './AddressedBinaryMessage';
import { AddressedSafetyMessage } from './AddressedSafetyMessage';
import { AidsToNavigationReport } from './AidsToNavigationReport';
import { AssignedModeCommand } from './AssignedModeCommand';
import { BaseStationReport } from './BaseStationReport';
import { BinaryAcknowledge } from './BinaryAcknowledge';
import { BinaryBroadcastMessage } from './BinaryBroadcastMessage';
import { ChannelManagement } from './ChannelManagement';
import { CoordinatedUTCInquiry } from './CoordinatedUTCInquiry';
import { DataLinkManagementMessage } from './DataLinkManagementMessage';
import { DataLinkManagementMessageData } from './DataLinkManagementMessageData';
import { ExtendedClassBPositionReport } from './ExtendedClassBPositionReport';
import { GnssBroadcastBinaryMessage } from './GnssBroadcastBinaryMessage';
import { GroupAssignmentCommand } from './GroupAssignmentCommand';
import { Interrogation } from './Interrogation';
import { LongRangeAisBroadcastMessage } from './LongRangeAisBroadcastMessage';
import { MultiSlotBinaryMessage } from './MultiSlotBinaryMessage';
import { PositionReport } from './PositionReport';
import { SafetyBroadcastMessage } from './SafetyBroadcastMessage';
import { ShipStaticData } from './ShipStaticData';
import { SingleSlotBinaryMessage } from './SingleSlotBinaryMessage';
import { StandardClassBPositionReport } from './StandardClassBPositionReport';
import { StandardSearchAndRescueAircraftReport } from './StandardSearchAndRescueAircraftReport';
import { StaticDataReport } from './StaticDataReport';
import { UnknownMessage } from './UnknownMessage';
import { HttpFile } from '../http/http';

export class AisStreamMessageMessage {
    'positionReport'?: PositionReport;
    'unknownMessage'?: UnknownMessage;
    'addressedSafetyMessage'?: AddressedSafetyMessage;
    'addressedBinaryMessage'?: AddressedBinaryMessage;
    'aidsToNavigationReport'?: AidsToNavigationReport;
    'assignedModeCommand'?: AssignedModeCommand;
    'baseStationReport'?: BaseStationReport;
    'binaryAcknowledge'?: BinaryAcknowledge;
    'binaryBroadcastMessage'?: BinaryBroadcastMessage;
    'channelManagement'?: ChannelManagement;
    'coordinatedUTCInquiry'?: CoordinatedUTCInquiry;
    'dataLinkManagementMessage'?: DataLinkManagementMessage;
    'dataLinkManagementMessageData'?: DataLinkManagementMessageData;
    'extendedClassBPositionReport'?: ExtendedClassBPositionReport;
    'gnssBroadcastBinaryMessage'?: GnssBroadcastBinaryMessage;
    'groupAssignmentCommand'?: GroupAssignmentCommand;
    'interrogation'?: Interrogation;
    'longRangeAisBroadcastMessage'?: LongRangeAisBroadcastMessage;
    'multiSlotBinaryMessage'?: MultiSlotBinaryMessage;
    'safetyBroadcastMessage'?: SafetyBroadcastMessage;
    'shipStaticData'?: ShipStaticData;
    'singleSlotBinaryMessage'?: SingleSlotBinaryMessage;
    'standardClassBPositionReport'?: StandardClassBPositionReport;
    'standardSearchAndRescueAircraftReport'?: StandardSearchAndRescueAircraftReport;
    'staticDataReport'?: StaticDataReport;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "positionReport",
            "baseName": "PositionReport",
            "type": "PositionReport",
            "format": ""
        },
        {
            "name": "unknownMessage",
            "baseName": "UnknownMessage",
            "type": "UnknownMessage",
            "format": ""
        },
        {
            "name": "addressedSafetyMessage",
            "baseName": "AddressedSafetyMessage",
            "type": "AddressedSafetyMessage",
            "format": ""
        },
        {
            "name": "addressedBinaryMessage",
            "baseName": "AddressedBinaryMessage",
            "type": "AddressedBinaryMessage",
            "format": ""
        },
        {
            "name": "aidsToNavigationReport",
            "baseName": "AidsToNavigationReport",
            "type": "AidsToNavigationReport",
            "format": ""
        },
        {
            "name": "assignedModeCommand",
            "baseName": "AssignedModeCommand",
            "type": "AssignedModeCommand",
            "format": ""
        },
        {
            "name": "baseStationReport",
            "baseName": "BaseStationReport",
            "type": "BaseStationReport",
            "format": ""
        },
        {
            "name": "binaryAcknowledge",
            "baseName": "BinaryAcknowledge",
            "type": "BinaryAcknowledge",
            "format": ""
        },
        {
            "name": "binaryBroadcastMessage",
            "baseName": "BinaryBroadcastMessage",
            "type": "BinaryBroadcastMessage",
            "format": ""
        },
        {
            "name": "channelManagement",
            "baseName": "ChannelManagement",
            "type": "ChannelManagement",
            "format": ""
        },
        {
            "name": "coordinatedUTCInquiry",
            "baseName": "CoordinatedUTCInquiry",
            "type": "CoordinatedUTCInquiry",
            "format": ""
        },
        {
            "name": "dataLinkManagementMessage",
            "baseName": "DataLinkManagementMessage",
            "type": "DataLinkManagementMessage",
            "format": ""
        },
        {
            "name": "dataLinkManagementMessageData",
            "baseName": "DataLinkManagementMessageData",
            "type": "DataLinkManagementMessageData",
            "format": ""
        },
        {
            "name": "extendedClassBPositionReport",
            "baseName": "ExtendedClassBPositionReport",
            "type": "ExtendedClassBPositionReport",
            "format": ""
        },
        {
            "name": "gnssBroadcastBinaryMessage",
            "baseName": "GnssBroadcastBinaryMessage",
            "type": "GnssBroadcastBinaryMessage",
            "format": ""
        },
        {
            "name": "groupAssignmentCommand",
            "baseName": "GroupAssignmentCommand",
            "type": "GroupAssignmentCommand",
            "format": ""
        },
        {
            "name": "interrogation",
            "baseName": "Interrogation",
            "type": "Interrogation",
            "format": ""
        },
        {
            "name": "longRangeAisBroadcastMessage",
            "baseName": "LongRangeAisBroadcastMessage",
            "type": "LongRangeAisBroadcastMessage",
            "format": ""
        },
        {
            "name": "multiSlotBinaryMessage",
            "baseName": "MultiSlotBinaryMessage",
            "type": "MultiSlotBinaryMessage",
            "format": ""
        },
        {
            "name": "safetyBroadcastMessage",
            "baseName": "SafetyBroadcastMessage",
            "type": "SafetyBroadcastMessage",
            "format": ""
        },
        {
            "name": "shipStaticData",
            "baseName": "ShipStaticData",
            "type": "ShipStaticData",
            "format": ""
        },
        {
            "name": "singleSlotBinaryMessage",
            "baseName": "SingleSlotBinaryMessage",
            "type": "SingleSlotBinaryMessage",
            "format": ""
        },
        {
            "name": "standardClassBPositionReport",
            "baseName": "StandardClassBPositionReport",
            "type": "StandardClassBPositionReport",
            "format": ""
        },
        {
            "name": "standardSearchAndRescueAircraftReport",
            "baseName": "StandardSearchAndRescueAircraftReport",
            "type": "StandardSearchAndRescueAircraftReport",
            "format": ""
        },
        {
            "name": "staticDataReport",
            "baseName": "StaticDataReport",
            "type": "StaticDataReport",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AisStreamMessageMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

