/**
 * Ais-Stream WebsocketObjects
 * A sample API to illustrate OpenAPI concepts
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChannelManagementUnicast {
    'addressStation1': number;
    'spare2': number;
    'addressStation2': number;
    'spare3': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "addressStation1",
            "baseName": "AddressStation1",
            "type": "number",
            "format": ""
        },
        {
            "name": "spare2",
            "baseName": "Spare2",
            "type": "number",
            "format": ""
        },
        {
            "name": "addressStation2",
            "baseName": "AddressStation2",
            "type": "number",
            "format": ""
        },
        {
            "name": "spare3",
            "baseName": "Spare3",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChannelManagementUnicast.attributeTypeMap;
    }

    public constructor() {
    }
}

