/**
 * Ais-Stream WebsocketObjects
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LongRangeAisBroadcastMessage {
    'messageID': number;
    'repeatIndicator': number;
    'userID': number;
    'valid': boolean;
    'positionAccuracy': boolean;
    'raim': boolean;
    'navigationalStatus': number;
    'longitude': number;
    'latitude': number;
    'sog': number;
    'cog': number;
    'positionLatency': boolean;
    'spare': boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageID",
            "baseName": "MessageID",
            "type": "number",
            "format": ""
        },
        {
            "name": "repeatIndicator",
            "baseName": "RepeatIndicator",
            "type": "number",
            "format": ""
        },
        {
            "name": "userID",
            "baseName": "UserID",
            "type": "number",
            "format": ""
        },
        {
            "name": "valid",
            "baseName": "Valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "positionAccuracy",
            "baseName": "PositionAccuracy",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "raim",
            "baseName": "Raim",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "navigationalStatus",
            "baseName": "NavigationalStatus",
            "type": "number",
            "format": ""
        },
        {
            "name": "longitude",
            "baseName": "Longitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "latitude",
            "baseName": "Latitude",
            "type": "number",
            "format": "double"
        },
        {
            "name": "sog",
            "baseName": "Sog",
            "type": "number",
            "format": "double"
        },
        {
            "name": "cog",
            "baseName": "Cog",
            "type": "number",
            "format": "double"
        },
        {
            "name": "positionLatency",
            "baseName": "PositionLatency",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "spare",
            "baseName": "Spare",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LongRangeAisBroadcastMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

