/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing BinaryBroadcastMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BinaryBroadcastMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BinaryBroadcastMessage
        //private BinaryBroadcastMessage instance;

        public BinaryBroadcastMessageTests()
        {
            // TODO uncomment below to create an instance of BinaryBroadcastMessage
            //instance = new BinaryBroadcastMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BinaryBroadcastMessage
        /// </summary>
        [Fact]
        public void BinaryBroadcastMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" BinaryBroadcastMessage
            //Assert.IsType<BinaryBroadcastMessage>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare'
        /// </summary>
        [Fact]
        public void SpareTest()
        {
            // TODO unit test for the property 'Spare'
        }

        /// <summary>
        /// Test the property 'ApplicationID'
        /// </summary>
        [Fact]
        public void ApplicationIDTest()
        {
            // TODO unit test for the property 'ApplicationID'
        }

        /// <summary>
        /// Test the property 'BinaryData'
        /// </summary>
        [Fact]
        public void BinaryDataTest()
        {
            // TODO unit test for the property 'BinaryData'
        }
    }
}
