/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing CoordinatedUTCInquiry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoordinatedUTCInquiryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CoordinatedUTCInquiry
        //private CoordinatedUTCInquiry instance;

        public CoordinatedUTCInquiryTests()
        {
            // TODO uncomment below to create an instance of CoordinatedUTCInquiry
            //instance = new CoordinatedUTCInquiry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CoordinatedUTCInquiry
        /// </summary>
        [Fact]
        public void CoordinatedUTCInquiryInstanceTest()
        {
            // TODO uncomment below to test "IsType" CoordinatedUTCInquiry
            //Assert.IsType<CoordinatedUTCInquiry>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare1'
        /// </summary>
        [Fact]
        public void Spare1Test()
        {
            // TODO unit test for the property 'Spare1'
        }

        /// <summary>
        /// Test the property 'DestinationID'
        /// </summary>
        [Fact]
        public void DestinationIDTest()
        {
            // TODO unit test for the property 'DestinationID'
        }

        /// <summary>
        /// Test the property 'Spare2'
        /// </summary>
        [Fact]
        public void Spare2Test()
        {
            // TODO unit test for the property 'Spare2'
        }
    }
}
