/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing ExtendedClassBPositionReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExtendedClassBPositionReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExtendedClassBPositionReport
        //private ExtendedClassBPositionReport instance;

        public ExtendedClassBPositionReportTests()
        {
            // TODO uncomment below to create an instance of ExtendedClassBPositionReport
            //instance = new ExtendedClassBPositionReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExtendedClassBPositionReport
        /// </summary>
        [Fact]
        public void ExtendedClassBPositionReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExtendedClassBPositionReport
            //Assert.IsType<ExtendedClassBPositionReport>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare1'
        /// </summary>
        [Fact]
        public void Spare1Test()
        {
            // TODO unit test for the property 'Spare1'
        }

        /// <summary>
        /// Test the property 'Sog'
        /// </summary>
        [Fact]
        public void SogTest()
        {
            // TODO unit test for the property 'Sog'
        }

        /// <summary>
        /// Test the property 'PositionAccuracy'
        /// </summary>
        [Fact]
        public void PositionAccuracyTest()
        {
            // TODO unit test for the property 'PositionAccuracy'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Cog'
        /// </summary>
        [Fact]
        public void CogTest()
        {
            // TODO unit test for the property 'Cog'
        }

        /// <summary>
        /// Test the property 'TrueHeading'
        /// </summary>
        [Fact]
        public void TrueHeadingTest()
        {
            // TODO unit test for the property 'TrueHeading'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Spare2'
        /// </summary>
        [Fact]
        public void Spare2Test()
        {
            // TODO unit test for the property 'Spare2'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Dimension'
        /// </summary>
        [Fact]
        public void DimensionTest()
        {
            // TODO unit test for the property 'Dimension'
        }

        /// <summary>
        /// Test the property 'FixType'
        /// </summary>
        [Fact]
        public void FixTypeTest()
        {
            // TODO unit test for the property 'FixType'
        }

        /// <summary>
        /// Test the property 'Raim'
        /// </summary>
        [Fact]
        public void RaimTest()
        {
            // TODO unit test for the property 'Raim'
        }

        /// <summary>
        /// Test the property 'Dte'
        /// </summary>
        [Fact]
        public void DteTest()
        {
            // TODO unit test for the property 'Dte'
        }

        /// <summary>
        /// Test the property 'AssignedMode'
        /// </summary>
        [Fact]
        public void AssignedModeTest()
        {
            // TODO unit test for the property 'AssignedMode'
        }

        /// <summary>
        /// Test the property 'Spare3'
        /// </summary>
        [Fact]
        public void Spare3Test()
        {
            // TODO unit test for the property 'Spare3'
        }
    }
}
