/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing GroupAssignmentCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GroupAssignmentCommandTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GroupAssignmentCommand
        //private GroupAssignmentCommand instance;

        public GroupAssignmentCommandTests()
        {
            // TODO uncomment below to create an instance of GroupAssignmentCommand
            //instance = new GroupAssignmentCommand();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GroupAssignmentCommand
        /// </summary>
        [Fact]
        public void GroupAssignmentCommandInstanceTest()
        {
            // TODO uncomment below to test "IsType" GroupAssignmentCommand
            //Assert.IsType<GroupAssignmentCommand>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare1'
        /// </summary>
        [Fact]
        public void Spare1Test()
        {
            // TODO unit test for the property 'Spare1'
        }

        /// <summary>
        /// Test the property 'Longitude1'
        /// </summary>
        [Fact]
        public void Longitude1Test()
        {
            // TODO unit test for the property 'Longitude1'
        }

        /// <summary>
        /// Test the property 'Latitude1'
        /// </summary>
        [Fact]
        public void Latitude1Test()
        {
            // TODO unit test for the property 'Latitude1'
        }

        /// <summary>
        /// Test the property 'Longitude2'
        /// </summary>
        [Fact]
        public void Longitude2Test()
        {
            // TODO unit test for the property 'Longitude2'
        }

        /// <summary>
        /// Test the property 'Latitude2'
        /// </summary>
        [Fact]
        public void Latitude2Test()
        {
            // TODO unit test for the property 'Latitude2'
        }

        /// <summary>
        /// Test the property 'StationType'
        /// </summary>
        [Fact]
        public void StationTypeTest()
        {
            // TODO unit test for the property 'StationType'
        }

        /// <summary>
        /// Test the property 'ShipType'
        /// </summary>
        [Fact]
        public void ShipTypeTest()
        {
            // TODO unit test for the property 'ShipType'
        }

        /// <summary>
        /// Test the property 'Spare2'
        /// </summary>
        [Fact]
        public void Spare2Test()
        {
            // TODO unit test for the property 'Spare2'
        }

        /// <summary>
        /// Test the property 'TxRxMode'
        /// </summary>
        [Fact]
        public void TxRxModeTest()
        {
            // TODO unit test for the property 'TxRxMode'
        }

        /// <summary>
        /// Test the property 'ReportingInterval'
        /// </summary>
        [Fact]
        public void ReportingIntervalTest()
        {
            // TODO unit test for the property 'ReportingInterval'
        }

        /// <summary>
        /// Test the property 'QuietTime'
        /// </summary>
        [Fact]
        public void QuietTimeTest()
        {
            // TODO unit test for the property 'QuietTime'
        }

        /// <summary>
        /// Test the property 'Spare3'
        /// </summary>
        [Fact]
        public void Spare3Test()
        {
            // TODO unit test for the property 'Spare3'
        }
    }
}
