/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing Interrogation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InterrogationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Interrogation
        //private Interrogation instance;

        public InterrogationTests()
        {
            // TODO uncomment below to create an instance of Interrogation
            //instance = new Interrogation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Interrogation
        /// </summary>
        [Fact]
        public void InterrogationInstanceTest()
        {
            // TODO uncomment below to test "IsType" Interrogation
            //Assert.IsType<Interrogation>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare'
        /// </summary>
        [Fact]
        public void SpareTest()
        {
            // TODO unit test for the property 'Spare'
        }

        /// <summary>
        /// Test the property 'Station1Msg1'
        /// </summary>
        [Fact]
        public void Station1Msg1Test()
        {
            // TODO unit test for the property 'Station1Msg1'
        }

        /// <summary>
        /// Test the property 'Station1Msg2'
        /// </summary>
        [Fact]
        public void Station1Msg2Test()
        {
            // TODO unit test for the property 'Station1Msg2'
        }

        /// <summary>
        /// Test the property 'Station2'
        /// </summary>
        [Fact]
        public void Station2Test()
        {
            // TODO unit test for the property 'Station2'
        }
    }
}
