/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing InterrogationStation1Msg2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InterrogationStation1Msg2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InterrogationStation1Msg2
        //private InterrogationStation1Msg2 instance;

        public InterrogationStation1Msg2Tests()
        {
            // TODO uncomment below to create an instance of InterrogationStation1Msg2
            //instance = new InterrogationStation1Msg2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InterrogationStation1Msg2
        /// </summary>
        [Fact]
        public void InterrogationStation1Msg2InstanceTest()
        {
            // TODO uncomment below to test "IsType" InterrogationStation1Msg2
            //Assert.IsType<InterrogationStation1Msg2>(instance);
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Spare'
        /// </summary>
        [Fact]
        public void SpareTest()
        {
            // TODO unit test for the property 'Spare'
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'SlotOffset'
        /// </summary>
        [Fact]
        public void SlotOffsetTest()
        {
            // TODO unit test for the property 'SlotOffset'
        }
    }
}
