/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing ShipStaticDataEta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipStaticDataEtaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipStaticDataEta
        //private ShipStaticDataEta instance;

        public ShipStaticDataEtaTests()
        {
            // TODO uncomment below to create an instance of ShipStaticDataEta
            //instance = new ShipStaticDataEta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipStaticDataEta
        /// </summary>
        [Fact]
        public void ShipStaticDataEtaInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipStaticDataEta
            //Assert.IsType<ShipStaticDataEta>(instance);
        }

        /// <summary>
        /// Test the property 'Month'
        /// </summary>
        [Fact]
        public void MonthTest()
        {
            // TODO unit test for the property 'Month'
        }

        /// <summary>
        /// Test the property 'Day'
        /// </summary>
        [Fact]
        public void DayTest()
        {
            // TODO unit test for the property 'Day'
        }

        /// <summary>
        /// Test the property 'Hour'
        /// </summary>
        [Fact]
        public void HourTest()
        {
            // TODO unit test for the property 'Hour'
        }

        /// <summary>
        /// Test the property 'Minute'
        /// </summary>
        [Fact]
        public void MinuteTest()
        {
            // TODO unit test for the property 'Minute'
        }
    }
}
