/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing ShipStaticDataDimension
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShipStaticDataDimensionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShipStaticDataDimension
        //private ShipStaticDataDimension instance;

        public ShipStaticDataDimensionTests()
        {
            // TODO uncomment below to create an instance of ShipStaticDataDimension
            //instance = new ShipStaticDataDimension();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShipStaticDataDimension
        /// </summary>
        [Fact]
        public void ShipStaticDataDimensionInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShipStaticDataDimension
            //Assert.IsType<ShipStaticDataDimension>(instance);
        }

        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Fact]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }

        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Fact]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }

        /// <summary>
        /// Test the property 'C'
        /// </summary>
        [Fact]
        public void CTest()
        {
            // TODO unit test for the property 'C'
        }

        /// <summary>
        /// Test the property 'D'
        /// </summary>
        [Fact]
        public void DTest()
        {
            // TODO unit test for the property 'D'
        }
    }
}
