/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing StandardSearchAndRescueAircraftReport
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StandardSearchAndRescueAircraftReportTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StandardSearchAndRescueAircraftReport
        //private StandardSearchAndRescueAircraftReport instance;

        public StandardSearchAndRescueAircraftReportTests()
        {
            // TODO uncomment below to create an instance of StandardSearchAndRescueAircraftReport
            //instance = new StandardSearchAndRescueAircraftReport();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StandardSearchAndRescueAircraftReport
        /// </summary>
        [Fact]
        public void StandardSearchAndRescueAircraftReportInstanceTest()
        {
            // TODO uncomment below to test "IsType" StandardSearchAndRescueAircraftReport
            //Assert.IsType<StandardSearchAndRescueAircraftReport>(instance);
        }

        /// <summary>
        /// Test the property 'MessageID'
        /// </summary>
        [Fact]
        public void MessageIDTest()
        {
            // TODO unit test for the property 'MessageID'
        }

        /// <summary>
        /// Test the property 'RepeatIndicator'
        /// </summary>
        [Fact]
        public void RepeatIndicatorTest()
        {
            // TODO unit test for the property 'RepeatIndicator'
        }

        /// <summary>
        /// Test the property 'UserID'
        /// </summary>
        [Fact]
        public void UserIDTest()
        {
            // TODO unit test for the property 'UserID'
        }

        /// <summary>
        /// Test the property 'Valid'
        /// </summary>
        [Fact]
        public void ValidTest()
        {
            // TODO unit test for the property 'Valid'
        }

        /// <summary>
        /// Test the property 'Altitude'
        /// </summary>
        [Fact]
        public void AltitudeTest()
        {
            // TODO unit test for the property 'Altitude'
        }

        /// <summary>
        /// Test the property 'Sog'
        /// </summary>
        [Fact]
        public void SogTest()
        {
            // TODO unit test for the property 'Sog'
        }

        /// <summary>
        /// Test the property 'PositionAccuracy'
        /// </summary>
        [Fact]
        public void PositionAccuracyTest()
        {
            // TODO unit test for the property 'PositionAccuracy'
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Cog'
        /// </summary>
        [Fact]
        public void CogTest()
        {
            // TODO unit test for the property 'Cog'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'AltFromBaro'
        /// </summary>
        [Fact]
        public void AltFromBaroTest()
        {
            // TODO unit test for the property 'AltFromBaro'
        }

        /// <summary>
        /// Test the property 'Spare1'
        /// </summary>
        [Fact]
        public void Spare1Test()
        {
            // TODO unit test for the property 'Spare1'
        }

        /// <summary>
        /// Test the property 'Dte'
        /// </summary>
        [Fact]
        public void DteTest()
        {
            // TODO unit test for the property 'Dte'
        }

        /// <summary>
        /// Test the property 'Spare2'
        /// </summary>
        [Fact]
        public void Spare2Test()
        {
            // TODO unit test for the property 'Spare2'
        }

        /// <summary>
        /// Test the property 'AssignedMode'
        /// </summary>
        [Fact]
        public void AssignedModeTest()
        {
            // TODO unit test for the property 'AssignedMode'
        }

        /// <summary>
        /// Test the property 'Raim'
        /// </summary>
        [Fact]
        public void RaimTest()
        {
            // TODO unit test for the property 'Raim'
        }

        /// <summary>
        /// Test the property 'CommunicationStateIsItdma'
        /// </summary>
        [Fact]
        public void CommunicationStateIsItdmaTest()
        {
            // TODO unit test for the property 'CommunicationStateIsItdma'
        }

        /// <summary>
        /// Test the property 'CommunicationState'
        /// </summary>
        [Fact]
        public void CommunicationStateTest()
        {
            // TODO unit test for the property 'CommunicationState'
        }
    }
}
