/*
 * Ais-Stream WebsocketObjects
 *
 * OpenAPI 3.0 definitions for the data models used by aisstream.io.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using Xunit;

namespace aisStream.Test.Model
{
    /// <summary>
    ///  Class for testing UnknownMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UnknownMessageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UnknownMessage
        //private UnknownMessage instance;

        public UnknownMessageTests()
        {
            // TODO uncomment below to create an instance of UnknownMessage
            //instance = new UnknownMessage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UnknownMessage
        /// </summary>
        [Fact]
        public void UnknownMessageInstanceTest()
        {
            // TODO uncomment below to test "IsType" UnknownMessage
            //Assert.IsType<UnknownMessage>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
